### ISSUE TITLE
flatpak run fails

### ISSUE THREAD

**Issue by tidux** [flathub/org.qutebrowser.qutebrowser#21]
```
$ flatpak run org.qutebrowser.qutebrowser
Traceback (most recent call last):
  File "/app/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.1.0', 'gui_scripts', 'qutebrowser')())
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/qutebrowser.py", line 218, in main
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/app.py", line 89, in run
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/utils/standarddir.py", line 347, in init
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/utils/standarddir.py", line 338, in _init_dirs
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/utils/standarddir.py", line 239, in _init_runtime
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'FLATPAK_ID'
```

**Comment by tinywrkb** [comment]
Which version of Flatpak are you running?

**Comment by tidux** [comment]
Flatpak 1.0.9, Ubuntu 18.04.

**Comment by tinywrkb** [comment]
Does this happen on with a clean profile? can you remove/move `~.var/app/org.qutebrowser.qutebrowser` and test?  
Is this x86_64 or aarch64?

Can you try starting the app manually from inside the sandbox like the example and also post the output:  
```
flatpak run --command=sh org.qutebrowser.qutebrowser
echo $FLATPAK_ID
qutebrowser
```

Can you upload a verbose log? as a file upload please not as a text post.
```
flatpak run org.qutebrowser.qutebrowser  -l debug
```

Can you try please the test build from #22? you should run it like this
```
flatpak run --user org.qutebrowser.qutebrowser//test
```

**Comment by tidux** [comment]
This is amd64/x86_64.  Issue persists with a clean profile.

```
$ flatpak run --command=sh org.qutebrowser.qutebrowser
sh-5.1$ qutebrowser
Traceback (most recent call last):
  File "/app/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.1.0', 'gui_scripts', 'qutebrowser')())
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/qutebrowser.py", line 218, in main
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/app.py", line 89, in run
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/utils/standarddir.py", line 347, in init
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/utils/standarddir.py", line 338, in _init_dirs
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/utils/standarddir.py", line 239, in _init_runtime
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'FLATPAK_ID'
sh-5.1$ 
```
Debug log is short enough to paste here as well.

```
$ flatpak run org.qutebrowser.qutebrowser -l debug 2>&1 | tee /tmp/flatpak.log
11:42:44 DEBUG    init       earlyinit:init_log:266 Log initialized.
11:42:44 DEBUG    init       app:run:86 Main process PID: 2
11:42:44 DEBUG    init       app:run:88 Initializing directories...
11:42:44 DEBUG    init       standarddir:init:345 Base directory: None
11:42:44 DEBUG    misc       standarddir:_writable_location:268 writable location for ConfigLocation: /home/tidux/.var/app/org.qutebrowser.qutebrowser/config
11:42:44 DEBUG    misc       standarddir:_writable_location:268 writable location for AppDataLocation: /home/tidux/.var/app/org.qutebrowser.qutebrowser/data
11:42:44 DEBUG    misc       standarddir:_writable_location:268 writable location for CacheLocation: /home/tidux/.var/app/org.qutebrowser.qutebrowser/cache
11:42:44 DEBUG    misc       standarddir:_writable_location:268 writable location for DownloadLocation: /home/tidux/Downloads
11:42:44 DEBUG    misc       standarddir:_writable_location:268 writable location for RuntimeLocation: /run/user/1000
Traceback (most recent call last):
  File "/app/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.1.0', 'gui_scripts', 'qutebrowser')())
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/qutebrowser.py", line 218, in main
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/app.py", line 89, in run
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/utils/standarddir.py", line 347, in init
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/utils/standarddir.py", line 338, in _init_dirs
  File "/app/lib/python3.8/site-packages/qutebrowser-2.1.0-py3.8.egg/qutebrowser/utils/standarddir.py", line 239, in _init_runtime
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'FLATPAK_ID'
```

**Comment by The-Compiler** [comment]
As a quick&dirty fix, this should work:

```diff
diff --git a/qutebrowser/utils/standarddir.py b/qutebrowser/utils/standarddir.py
index 057d2627b..3ddde67c7 100644
--- a/qutebrowser/utils/standarddir.py
+++ b/qutebrowser/utils/standarddir.py
@@ -240,7 +240,8 @@ def _init_runtime(args: Optional[argparse.Namespace]) -> None:
             # instances.
             *parts, app_name = os.path.split(path)
             assert app_name == APPNAME, app_name
-            path = os.path.join(*parts, 'app', os.environ['FLATPAK_ID'])
+            flatpak_id = os.environ.get('FLATPAK_ID', 'org.qutebrowser.qutebrowser')
+            path = os.path.join(*parts, 'app', flatpak_id)
 
     _create(path)
     _locations[_Location.runtime] = path
```

I'll look into parsing `/.flatpak-info` if `FLATPAK_ID` is unavailable tomorrow or so, off to bed now.

**Comment by tinywrkb** [comment]
@tidux can you test the latest test build from #22 

> Build [43455 successful](https://flathub.org/builds/#/builders/32/builds/43455)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/41808/org.qutebrowser.qutebrowser.flatpakref
> ```

**Comment by tidux** [comment]
This mostly works, but H.264 videos are broken.  I think the package needs a dependency on `org.freedesktop.Platform.ffmpeg-full` for full functionality.  Based on my experience on other platforms, Qutebrowser *should* pick up ffmpeg if it's available to the dynamic linker.

**Comment by tinywrkb** [comment]
@tidux thanks for the feedback. I merged the Flatpak_ID fix with #21.

I can replicate the H.264 playback issue. I will do the same as Mozilla and make it an optional dependency and add some notes about it somewhere, maybe in the wiki and Flathub page. You can follow in #24.

**Comment by tinywrkb** [comment]
p.s. thanks @The-Compiler!

**Comment by tinywrkb** [comment]
> Could you try the [full patch](https://github.com/qutebrowser/qutebrowser/commit/8b49d87526dd34380df6e98800ecc82367b48be1.patch) (on top of the earlier one)?
> 
> I don't have easy access to an older Flatpak, so this is totally untested at the moment (other than the unit test).

I tested in a Xubuntu 18.04 VM and it is working as expected.  
Maybe @tidux want also to confirm? after installing the test build just run `flatpak run --user org.qutebrowser.qutebrowser//test`.

> Build [43520 successful](https://flathub.org/builds/#/builders/32/builds/43520)
> To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/41869/org.qutebrowser.qutebrowser.flatpakref
> ```

I had to manually apply the patch and at this point, I would really prefer to drop the patches and check-out v2.1.x branch.

**Comment by tidux** [comment]
Yep, latest test patch works.  Will be very nice to get this all mainlined.

**Comment by tinywrkb** [comment]
@tidux thanks again for testing. We would be able to drop all the Flatpak related patches in the next stable release.
